### ISSUE TITLE
Circle.ci

### ISSUE THREAD

**Issue by lremus** [Edouard360/text-mining-challenge#2]
What is it?

**Comment by Edouard360** [comment]
I found it originally in the [coveralls-python](https://github.com/coveralls-clients/coveralls-python)  repo which serves as an example for using the coveralls API in python. In the end, it is not needed in our case, as circleci is just a travis competitor.

But look for yourself at their customers. [Circleci](https://circleci.com/customers/) vs [Travis](https://travis-ci.com/).

**Comment by lremus** [comment]
Thanks !
